/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type CategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'category';
};

export type BrandReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'brand';
};

export type ProductVariantReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productVariant';
};

export type ProductWeightReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productWeight';
};

export type ProductSizeReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productSize';
};

export type ProductColorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'productColor';
};

export type VendorProduct = {
  _id: string;
  _type: 'vendorProduct';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  vendorEmail?: string;
  vendorName?: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  variant?: ProductVariantReference;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  profitMargin?: number;
  vendorProductStatus?:
    | 'draft'
    | 'pending'
    | 'approved'
    | 'rejected'
    | 'active'
    | 'inactive'
    | 'pending_deactivation'
    | 'pending_activation';
  approvalStatus?: 'awaiting' | 'approved' | 'rejected';
  rejectionReason?: string;
  submittedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
  mainProductId?: string;
  totalSales?: number;
  totalRevenue?: number;
  totalProfit?: number;
  lastOrderDate?: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type UserReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'user';
};

export type VendorApplication = {
  _id: string;
  _type: 'vendorApplication';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  user?: UserReference;
  userId?: string;
  userEmail?: string;
  businessName?: string;
  businessType?:
    | 'individual'
    | 'partnership'
    | 'llc'
    | 'corporation'
    | 'cooperative';
  businessDescription?: string;
  businessAddress?: string;
  businessPhone?: string;
  businessEmail?: string;
  taxId?: string;
  websiteUrl?: string;
  productsCategory?:
    | 'fruits'
    | 'vegetables'
    | 'dairy'
    | 'meat'
    | 'bakery'
    | 'organic'
    | 'packaged'
    | 'beverages'
    | 'other';
  estimatedMonthlyRevenue?:
    | '0-1000'
    | '1000-5000'
    | '5000-10000'
    | '10000-25000'
    | '25000-50000'
    | '50000+';
  status?: 'pending' | 'reviewing' | 'approved' | 'rejected';
  appliedAt?: string;
  reviewedAt?: string;
  reviewedBy?: string;
  approvalNotes?: string;
  rejectionReason?: string;
  adminNotes?: string;
};

export type Store = {
  _id: string;
  _type: 'store';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  address?: {
    street?: string;
    house?: string;
    city?: string;
    state?: string;
    zipCode?: string;
    country?:
      | 'US'
      | 'CA'
      | 'BD'
      | 'UK'
      | 'AU'
      | 'DE'
      | 'FR'
      | 'ES'
      | 'IT'
      | 'NL'
      | 'BE'
      | 'CH'
      | 'AT'
      | 'PL'
      | 'SE'
      | 'NO'
      | 'DK'
      | 'FI'
      | 'IE'
      | 'PT'
      | 'GR'
      | 'CZ'
      | 'HU'
      | 'RO'
      | 'BG'
      | 'HR'
      | 'SK'
      | 'SI'
      | 'LU'
      | 'MT'
      | 'CY'
      | 'JP'
      | 'KR'
      | 'CN'
      | 'IN'
      | 'SG'
      | 'MY'
      | 'TH'
      | 'ID'
      | 'PH'
      | 'VN'
      | 'NZ'
      | 'ZA'
      | 'AE'
      | 'SA'
      | 'IL'
      | 'TR'
      | 'BR'
      | 'MX'
      | 'AR'
      | 'CL'
      | 'CO';
  };
  coordinates?: {
    lat?: number;
    lng?: number;
  };
  contact?: {
    phone?: string;
    email?: string;
  };
  hours?: {
    monday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    tuesday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    wednesday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    thursday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    friday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    saturday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
    sunday?: {
      open?: string;
      close?: string;
      closed?: boolean;
    };
  };
  description?: string;
  features?: Array<string>;
  isActive?: boolean;
  sortOrder?: number;
};

export type Subscription = {
  _id: string;
  _type: 'subscription';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  status?: 'active' | 'unsubscribed' | 'pending';
  subscribedAt?: string;
  unsubscribedAt?: string;
  source?: 'footer' | 'popup' | 'checkout' | 'other';
  ipAddress?: string;
  userAgent?: string;
};

export type ProductReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'product';
};

export type Review = {
  _id: string;
  _type: 'review';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  product?: ProductReference;
  user?: UserReference;
  rating?: number;
  title?: string;
  content?: string;
  isVerifiedPurchase?: boolean;
  status?: 'pending' | 'approved' | 'rejected';
  helpful?: number;
  helpfulBy?: Array<
    {
      _key: string;
    } & UserReference
  >;
  adminNotes?: string;
  createdAt?: string;
  updatedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
};

export type UserAccessRequest = {
  _id: string;
  _type: 'userAccessRequest';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  clerkUserId?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  status?: 'pending' | 'approved' | 'rejected';
  requestedAt?: string;
  approvedAt?: string;
  approvedBy?: UserReference;
  rejectedAt?: string;
  rejectedBy?: UserReference;
  notes?: string;
};

export type SentNotification = {
  _id: string;
  _type: 'sentNotification';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notificationId?: string;
  title?: string;
  message?: string;
  type?: 'promo' | 'order' | 'system' | 'marketing' | 'general';
  priority?: 'low' | 'medium' | 'high' | 'urgent';
  sentAt?: string;
  sentBy?: string;
  actionUrl?: string;
  recipientCount?: number;
  recipients?: Array<{
    email?: string;
    name?: string;
    delivered?: boolean;
    read?: boolean;
    readAt?: string;
    _key: string;
  }>;
};

export type Contact = {
  _id: string;
  _type: 'contact';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  subject?: string;
  message?: string;
  status?: 'new' | 'read' | 'replied' | 'closed';
  priority?: 'low' | 'medium' | 'high' | 'urgent';
  submittedAt?: string;
  ipAddress?: string;
  userAgent?: string;
};

export type Address = {
  _id: string;
  _type: 'address';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  user?: UserReference;
  phone?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  country?: string;
  countryCode?: string;
  stateCode?: string;
  subArea?: string;
  type?: 'home' | 'office' | 'other';
  default?: boolean;
  createdAt?: string;
};

export type AddressReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'address';
};

export type OrderReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'order';
};

export type User = {
  _id: string;
  _type: 'user';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firebaseUid?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  profileImageUrl?: string;
  addresses?: Array<
    {
      _key: string;
    } & AddressReference
  >;
  preferences?: {
    newsletter?: boolean;
    emailNotifications?: boolean;
    smsNotifications?: boolean;
    preferredCurrency?: 'USD' | 'EUR' | 'GBP' | 'CAD';
    preferredLanguage?: 'en' | 'es' | 'fr' | 'de';
  };
  rewardPoints?: number;
  wishlist?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  cart?: Array<{
    product?: ProductReference;
    quantity?: number;
    addedAt?: string;
    size?: string;
    color?: string;
    _key: string;
  }>;
  orders?: Array<
    {
      _key: string;
    } & OrderReference
  >;
  loyaltyPoints?: number;
  totalSpent?: number;
  walletBalance?: number;
  walletTransactions?: Array<{
    id?: string;
    type?:
      | 'credit_refund'
      | 'credit_manual'
      | 'debit_order'
      | 'debit_withdrawal';
    amount?: number;
    balanceBefore?: number;
    balanceAfter?: number;
    description?: string;
    orderId?: string;
    withdrawalRequestId?: string;
    processedBy?: string;
    createdAt?: string;
    status?: 'completed' | 'pending' | 'failed' | 'cancelled';
    _key: string;
  }>;
  withdrawalRequests?: Array<{
    id?: string;
    amount?: number;
    method?: 'bank' | 'paypal' | 'stripe' | 'check';
    bankDetails?: {
      accountHolderName?: string;
      bankName?: string;
      accountNumber?: string;
      routingNumber?: string;
      swiftCode?: string;
    };
    paypalEmail?: string;
    status?:
      | 'pending'
      | 'approved'
      | 'processing'
      | 'completed'
      | 'rejected'
      | 'cancelled';
    requestedAt?: string;
    processedAt?: string;
    processedBy?: string;
    rejectionReason?: string;
    notes?: string;
    transactionId?: string;
    _key: string;
  }>;
  lastLogin?: string;
  isActive?: boolean;
  isVendor?: boolean;
  vendorStatus?: 'none' | 'pending' | 'active' | 'rejected' | 'suspended';
  vendorAppliedAt?: string;
  vendorApprovedBy?: string;
  vendorApprovedAt?: string;
  vendorRejectedAt?: string;
  vendorRejectionReason?: string;
  vendorSuspendedAt?: string;
  vendorSuspendedBy?: string;
  vendorSuspensionReason?: string;
  vendorBusinessName?: string;
  vendorBusinessDescription?: string;
  vendorBusinessLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  vendorCommissionRate?: number;
  vendorPerformance?: {
    totalProducts?: number;
    activeProducts?: number;
    totalSales?: number;
    totalRevenue?: number;
    totalCommission?: number;
    averageRating?: number;
    totalReviews?: number;
  };
  isEmployee?: boolean;
  isAdmin?: boolean;
  employeeRole?:
    | 'callcenter'
    | 'packer'
    | 'warehouse'
    | 'deliveryman'
    | 'incharge'
    | 'accounts';
  employeeStatus?: 'active' | 'inactive' | 'suspended';
  employeeAssignedBy?: string;
  employeeAssignedAt?: string;
  employeeSuspendedBy?: string;
  employeeSuspendedAt?: string;
  employeeSuspensionReason?: string;
  employeePerformance?: {
    ordersProcessed?: number;
    ordersConfirmed?: number;
    ordersPacked?: number;
    ordersAssignedForDelivery?: number;
    ordersDelivered?: number;
    cashCollected?: number;
    paymentsReceived?: number;
    lastActiveAt?: string;
  };
  createdAt?: string;
  updatedAt?: string;
  notifications?: Array<{
    id?: string;
    title?: string;
    message?: string;
    type?: 'promo' | 'order' | 'system' | 'marketing' | 'general';
    read?: boolean;
    priority?: 'low' | 'medium' | 'high' | 'urgent';
    sentAt?: string;
    readAt?: string;
    sentBy?: string;
    actionUrl?: string;
    _key: string;
  }>;
};

export type Blogcategory = {
  _id: string;
  _type: 'blogcategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type BlogcategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'blogcategory';
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  blogcategories?: Array<
    {
      _key: string;
    } & BlogcategoryReference
  >;
  publishedAt?: string;
  isLatest?: boolean;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Banner = {
  _id: string;
  _type: 'banner';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  title?: string;
  buttonTitle?: string;
  buttonLink?: string;
};

export type CouponReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'coupon';
};

export type Order = {
  _id: string;
  _type: 'order';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  firebaseUid?: string;
  clerkPaymentId?: string;
  clerkPaymentStatus?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  sslcommerzTransactionId?: string;
  sslcommerzSessionKey?: string;
  sslcommerzValidationId?: string;
  sslcommerzBankTransactionId?: string;
  sslcommerzCardType?: string;
  sslcommerzCardIssuer?: string;
  sslcommerzCardBrand?: string;
  sslcommerzCardNo?: string;
  sslcommerzTransactionDate?: string;
  paidAt?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    _key: string;
  }>;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  productDiscount?: number;
  businessDiscount?: number;
  coupon?: {
    code?: string;
    discountType?: 'percentage' | 'fixed';
    discountValue?: number;
    discountAmount?: number;
    couponRef?: CouponReference;
  };
  address?: {
    state?: string;
    zip?: string;
    city?: string;
    address?: string;
    name?: string;
  };
  status?:
    | 'pending'
    | 'address_confirmed'
    | 'order_confirmed'
    | 'packed'
    | 'ready_for_delivery'
    | 'out_for_delivery'
    | 'delivered'
    | 'completed'
    | 'cancelled'
    | 'rescheduled'
    | 'failed_delivery';
  orderDate?: string;
  paymentStatus?: 'pending' | 'paid' | 'failed' | 'cancelled';
  paymentMethod?:
    | 'cash_on_delivery'
    | 'stripe'
    | 'sslcommerz'
    | 'clerk'
    | 'card';
  addressConfirmedBy?: string;
  addressConfirmedAt?: string;
  orderConfirmedBy?: string;
  orderConfirmedAt?: string;
  packedBy?: string;
  packedAt?: string;
  packingNotes?: string;
  assignedWarehouseBy?: string;
  assignedWarehouseAt?: string;
  dispatchedBy?: string;
  dispatchedAt?: string;
  assignedDeliverymanId?: string;
  assignedDeliverymanName?: string;
  deliveredBy?: string;
  deliveredAt?: string;
  deliveryNotes?: string;
  deliveryAttempts?: number;
  rescheduledDate?: string;
  rescheduledReason?: string;
  cashCollected?: boolean;
  cashCollectedAmount?: number;
  cashCollectedAt?: string;
  cashSubmittedToAccounts?: boolean;
  cashSubmittedBy?: string;
  cashSubmittedAt?: string;
  cashSubmissionNotes?: string;
  assignedAccountsEmployeeId?: string;
  assignedAccountsEmployeeName?: string;
  cashSubmissionStatus?: 'not_submitted' | 'pending' | 'confirmed' | 'rejected';
  cashSubmissionRejectionReason?: string;
  paymentReceivedBy?: string;
  paymentReceivedAt?: string;
  cancellationRequested?: boolean;
  cancellationRequestedAt?: string;
  cancellationRequestReason?: string;
  cancelledAt?: string;
  cancelledBy?: string;
  cancellationReason?: string;
  amountPaid?: number;
  refundedToWallet?: boolean;
  refundAmount?: number;
  statusHistory?: Array<{
    status?: string;
    changedBy?: string;
    changedByRole?:
      | 'admin'
      | 'callcenter'
      | 'packer'
      | 'warehouse'
      | 'deliveryman'
      | 'incharge'
      | 'accounts'
      | 'system';
    changedAt?: string;
    notes?: string;
    _key: string;
  }>;
};

export type Coupon = {
  _id: string;
  _type: 'coupon';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  code?: string;
  description?: string;
  discountType?: 'percentage' | 'fixed';
  discountValue?: number;
  minimumOrderAmount?: number;
  maxDiscountAmount?: number;
  usageLimit?: number;
  usageLimitPerUser?: number;
  timesUsed?: number;
  startDate?: string;
  expiryDate?: string;
  isActive?: boolean;
  isPublic?: boolean;
  applicableProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  applicableCategories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  excludedProducts?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  firstOrderOnly?: boolean;
  userRestrictions?: Array<string>;
  createdAt?: string;
};

export type ProductColor = {
  _id: string;
  _type: 'productColor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  hexCode?: string;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type ProductSize = {
  _id: string;
  _type: 'productSize';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  value?: string;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type ProductWeight = {
  _id: string;
  _type: 'productWeight';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  value?: string;
  unit?: 'g' | 'kg' | 'lb' | 'oz';
  numericValue?: number;
  isActive?: boolean;
  weight?: number;
  description?: string;
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
    _key: string;
  }>;
  description?: string;
  price?: number;
  baseWeight?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  brand?: BrandReference;
  status?: 'new' | 'hot' | 'sale';
  variant?: ProductVariantReference;
  hasWeights?: boolean;
  useAllWeights?: boolean;
  weights?: Array<
    {
      _key: string;
    } & ProductWeightReference
  >;
  hasVariants?: boolean;
  useAllSizes?: boolean;
  sizes?: Array<
    {
      _key: string;
    } & ProductSizeReference
  >;
  useAllColors?: boolean;
  colors?: Array<
    {
      _key: string;
    } & ProductColorReference
  >;
  isFeatured?: boolean;
  isOffer?: boolean;
  enableRatingsManagement?: boolean;
  averageRating?: number;
  totalReviews?: number;
  ratingDistribution?: {
    fiveStars?: number;
    fourStars?: number;
    threeStars?: number;
    twoStars?: number;
    oneStar?: number;
  };
};

export type ProductVariant = {
  _id: string;
  _type: 'productVariant';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  isActive?: boolean;
  weight?: number;
  seoTitle?: string;
  seoDescription?: string;
};

export type Brand = {
  _id: string;
  _type: 'brand';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CategoryReference
  | BrandReference
  | ProductVariantReference
  | ProductWeightReference
  | ProductSizeReference
  | ProductColorReference
  | VendorProduct
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | UserReference
  | VendorApplication
  | Store
  | Subscription
  | ProductReference
  | Review
  | UserAccessRequest
  | SentNotification
  | Contact
  | Address
  | AddressReference
  | OrderReference
  | User
  | Blogcategory
  | AuthorReference
  | BlogcategoryReference
  | Blog
  | BlockContent
  | Author
  | Banner
  | CouponReference
  | Order
  | Coupon
  | ProductColor
  | ProductSize
  | ProductWeight
  | Product
  | ProductVariant
  | Brand
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
